import type { Metadata } from "next";
import { Exo, Courier_Prime } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/globals/nav-bar";

const exo = Exo({
    variable: "--font-exo",
    subsets: ["latin"],
});

const courierPrime = Courier_Prime({
    variable: "--font-courier-prime",
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "Novium",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${exo.variable} ${courierPrime.variable} antialiased bg-novium-bg`}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
